services:
  cross-rpi-builder:
    image: cross-rpi-builder
    build:
      context: ./dockerfile
      args:
        TARGET_ARCH: arm-unknown-linux-gnueabihf
    container_name: cross-rpi-builder
    environment:
      - TARGET_ARCH=arm-unknown-linux-gnueabihf
      - LIBCLANG_INCLUDE_PATH=/usr/include/clang/7/include
      - LIBPIGPIO_LIB_PATH=/usr/lib
      - LIBPIGPIO_INCLUDE_PATH=/usr/include
    volumes:
      - .:/tmp/pigpio-sys
      - cargo-cache:/tmp/.cargo
    working_dir: /tmp/pigpio-sys
    command: |
      bash -c "
      cargo build --target=$${TARGET_ARCH}
      cargo build --target=$${TARGET_ARCH} --examples
      "

volumes:
  cargo-cache:
